POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "f3rr34dm1n$@ferre.com",
    "password": "l4f3rr3$"
}

###

GET http://localhost:5000/api/users
###

GET http://localhost:5000/api/employees

###

POST http://localhost:5000/api/employees
Content-Type: application/json

{
    "email": "f3rr34dm1n$@ferre.com",
    "password": "l4f3rr3$"
}

###

POST http://localhost:5000/api/employees/login
Content-Type: application/json

{
    "email": "f3rr34dm1n$@ferre.com",
    "password": "l4f3rr3$"
}

###
DELETE http://localhost:5000/api/employees/646bfaf15ac499fe23f7a0ec

###
DELETE http://localhost:5000/api/users/646bfe346f8d77cc3eda9317